### ISSUE TITLE
Paired end reads

### ISSUE THREAD

**Issue by andrewjmc** [SegataLab/panphlan#10]
Hello,

How do you recommend handling paired end reads?

Thanks,

Andrew

**Comment by leonarDubois** [comment]
Hello, 

For paired end reads, you can just merge all in a big fasta/fastq file and feed all to the script. Coverage is corrected and normalized based on median value, number of genes in the gene families and average length of genes. Moreover, you can display the coverage curve (arguement `--o_covplot_normed` in `panphlan_profiling.py`) and then adjust the thresholds for presence/absence detection. They are all the `--min_coverage, --left_max, --right_min, --th_non_present, --th_present and --th_multicopy` parameters. Usually we stick to the default value, but it can be relevant to play a bit with them to see if there’s a way to optimize the analysis.

I hope this answer all your question. Feel free to ask if you need more details.

**Comment by andrewjmc** [comment]
Many thanks.

Cheeky additional question (also posed in forum) - would you filter out host reads first (I.e. use bowtie unsigned reads) and would you filter out other organisms first?

Thanks,

Andrew
