### ISSUE TITLE
Track unknown strains

### ISSUE THREAD

**Issue by termithorbor** [SegataLab/panphlan#12]
Hi all,

panphlan claims to be able to track unkown strains but how is that possible? Because you allways have to supply a database like Ecoli. What if you do not know what bacteria species are in the sample?

Cheers

**Comment by leonarDubois** [comment]
Hello,

Indeed, one always need to provide a database of reference genomes to perform the PanPhlAn analysis. We claim to track unknown strains in the sense that each metagenomic sample can coutain one or several strains of the species of interest whose composition  in genes is unique. For example, you can have :

Reference genome 1 with genes A, B and C
Reference genome 2 with genes A, C and D
Reference genome 2 with genes B, D and E
Which gives you a pangnome of A-B-C-D-E

PanPhlAn will map the metagenomic reads against all of these genes. In some sample you can identify a already-known set of genes that can be identified as one of the reference genome (A-B-C or A-C-D or  B-D-E). In other case, you can get for example only genes B,C and E charachterized as present. This combinaision will not correpond to any known reference genome but will still be a strain of the species of interest.

I hope this answer your question. Feel free to ask if you need more details.
Cheers

**Comment by termithorbor** [comment]
So when I know that my sample contains for example different Ecoli strains but not all of them are known so far this is not a problem and also the unkown ones are identified as individul Ecoli strains. So for example I have in my sample Ecoli strains 1-3 which are known and 4-6 which are unkonwn, then the software can still tell me that I have 6 different strains together with their abundance - is that right? And can I do that in Panphlan or do I ne StrainPhlan as well?

**Comment by leonarDubois** [comment]
StrainPhlAn computes a phylogenetic distance between samples and PanPhlAn focuses on genes families presence/absence. Both PanPhlAn and StrainPhlAn study within-species diversity. They consider one strain per metagenomic sample. PanPhlAn coverage curve output can help identify if multilple strains are present. However, in both cases, the tool first purpose is not to identify multiple strains in the same sample. It is meant to be used with multiple samples to compar them on a strain-level

**Comment by termithorbor** [comment]
So this means I can not use it to identify how many ecoli strains are present in a single sample?

**Comment by leonarDubois** [comment]
No, sadly you cannot get the answer to how many strains are present. The best PanPhlAn can do is to assess if the strain detected in the sample for the given species is the only strain or if they are many
