### ISSUE TITLE
Meet “OSError: Invalid data stream” when using panphlan_profiling.py

### ISSUE THREAD

**Issue by siriusorignblack** [SegataLab/panphlan#19]
Hi,  @leonarDubois
I am new to panphlan3 and i meet error when i used panphlan_profiling.py.
The code i perform is as following:
(panphlan) wangzhenyu@wangzhenyudeMacBook-Pro panphlan % panphlan_profiling.py
-i ./map_results/
-p ./Bifidobacterium_pseudocatenulatum/Bifidobacterium_pseudocatenulatum_pangenome.tsv
–o_matrix ./profiling_results/matrix.csv

STEP 1. Processing genes informations from pangenome file…
Number of reference genomes: 18
Average number of gene-families per genome: 1761
Total number of pangenome gene-families 4550

STEP 2. Create coverage matrix
Traceback (most recent call last):
File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/bin/panphlan_profiling.py”, line 932, in
main()
File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/bin/panphlan_profiling.py”, line 864, in main
dna_samples_covs = read_map_results(args.i_dna, args.verbose)
File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/bin/panphlan_profiling.py”, line 299, in read_map_results
dna_samples_covs[dna_sample_id] = read_gene_cov_file(os.path.join(i_dna, dna_covs_file))
File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/bin/panphlan_profiling.py”, line 285, in read_gene_cov_file
for line in f:
File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/lib/python3.7/bz2.py”, line 215, in readline
return self._buffer.readline(size)
File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/lib/python3.7/_compression.py”, line 68, in readinto
data = self.read(len(byte_view))
File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/lib/python3.7/_compression.py”, line 103, in read
data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream

Thanks for viewing! 
hope for your reply.

**Comment by leonarDubois** [comment]
Hello,

thanks for pointing out this issue. It seems that the profiling step has trouble reading your results from the previous step (mapping step) or at least unzip them. Are your sure your input files (the ones in `./map_results/`) are bz2 compressed files as they should be at the end of the mapping step ? Also, do they contains any special character in the filename that could cause troubles, such as space characters ?

**Comment by siriusorignblack** [comment]
Hi, 
thanks for replying. 
The input file contained in map_results/ is as following:
(panphlan) wangzhenyu@wangzhenyudeMacBook-Pro map_results % ls
D35PC4_1_1.csv.bz2

I changed the file name and run again. But same error also occurred.

**Comment by leonarDubois** [comment]
Ok, try unzipping the file manually and check the content. Your should have 2 fields, gene names and a numeric value. If this is ok, then it means that the issue might come from the mapping file generation instead. Which command did you run on the mapping step ?

**Comment by siriusorignblack** [comment]
I unzip the file and the content looks like as following:
(panphlan) wangzhenyu@wangzhenyudeMacBook-Pro map_results % head D35PC.csv
DXD35_00015	20996
DXD35_00020	86501
DXD35_00025	68508
DXD35_00030	81754
amt	1224319
DXD35_00040	8485
DXD35_00045	14149
dnaB	2064436
DXD35_00055	123892
DXD35_00060	69630

The command i used to perform map step is :
(panphlan) wangzhenyu@wangzhenyudeMacBook-Pro map_results % panphlan_map.py \                      
-p ./Bifidobacterium_pseudocatenulatum/Bifidobacterium_pseudocatenulatum_pangenome.tsv \
--indexes Bifidobacterium_pseudocatenulatum/Bifidobacterium_pseudocatenulatum \
-i ./D35PC4_1.fastp.1.fq \
-o map_results/D35PC4_1_1.csv

**Comment by leonarDubois** [comment]
It is strange, because all the command use is fine and the results should be OK as well.
The error raised : 
`File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/lib/python3.7/bz2.py”, line 215, in readline
return self._buffer.readline(size)
File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/lib/python3.7/_compression.py”, line 68, in readinto
data = self.read(len(byte_view))
File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/lib/python3.7/_compression.py”, line 103, in read
data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream`

means that the file trying to be opened is not a bz2 compressed file. So either the file is corrupted somehow (version of the BZ2 python package, space on the disk....) or the map_results folder contains other non bz2 files that try to be opened

**Comment by siriusorignblack** [comment]
I check the integrity of mapping result file and it is OK.

The version of bzip2 package is as following:
(panphlan) wangzhenyu@wangzhenyudeMacBook-Pro Panphlan % conda list
# packages in environment at /Users/wangzhenyu/opt/miniconda3/envs/panphlan:
#
# Name                    Version                   Build  Channel
bowtie2                   2.4.1            py37h5e6fd57_3    bioconda
bzip2                     1.0.8                haf1e3a3_3    conda-forge
c-ares                    1.16.1               haf1e3a3_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
htslib                    1.10.2               h422799e_1    bioconda
joblib                    0.16.0                   pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
krb5                      1.17.1               h75d18d8_3    conda-forge
libcurl                   7.71.1               h9bf37e3_5    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libdeflate                1.6                  h0b31af3_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
matplotlib                3.3.1                    pypi_0    pypi
ncurses                   6.2                  hb1e8313_1    conda-forge
numpy                     1.19.2                   pypi_0    pypi
openssl                   1.1.1g               haf1e3a3_1    conda-forge
pandas                    1.1.2                    pypi_0    pypi
panphlan                  3.0                      pypi_0    pypi
perl                      5.30.3               h6156909_1    conda-forge
pillow                    7.2.0                    pypi_0    pypi
pip                       20.2.4                   pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.8           hc9dea61_1_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                   pypi_0    pypi
readline                  8.0                  h0678c8f_2    conda-forge
samtools                  1.10                 hf7e01e7_3    bioconda
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
seaborn                   0.11.0                   pypi_0    pypi
setuptools                49.6.0           py37hc8dfbb8_0    conda-forge
six                       1.15.0                   pypi_0    pypi
sqlite                    3.33.0               h960bd1c_0    conda-forge
tbb                       2019.9               ha1b3eb9_1    conda-forge
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1009    conda-forge

Is the version of bzip2 OK?

The disk spack is enough and I'm sure that map_results contain csv.bz2 file.
The input file contained in map_results/ is as following:
(panphlan) wangzhenyu@wangzhenyudeMacBook-Pro map_results % ls
D35PC4_1_1.csv.bz2

**Comment by leonarDubois** [comment]
Hi, 

I've been investigating the problem a bit more. The bz2 python package syntax changed a bit when it switched to Python 3.
I've pushed a tiny change on the repo that should modify the way the bz2 file is read. Let me know if it solve your problem

**Comment by siriusorignblack** [comment]
Hi, 
Thanks for spending so much time on solving my problem. 
I try again using the updated script. However, same error occurred again.

**Comment by siriusorignblack** [comment]
Hi, 
I have solved this problem when I change the output of mapping step in .tsv format.  
I guess this error result from words = line.strip().split('\t') within read_gene_cov_file(input_file). But i'm not familiar with python so i'm not sure that this is the bug of my error?

**Comment by leonarDubois** [comment]
Hi,

glad to know that the problem is solved. It is quite strange that the file extension caused the issue, since the coverage output file was written using tab separated fields ` '\t' ` in the `panphlan_map.py` script. So the file extension provided in the output name should not impact it. I'll investigate that more precisely when I'll have time.

**Comment by PabloArrow** [comment]
> Hi, @leonarDubois I am new to panphlan3 and i meet error when i used panphlan_profiling.py. The code i perform is as following: (panphlan) wangzhenyu@wangzhenyudeMacBook-Pro panphlan % panphlan_profiling.py -i ./map_results/ -p ./Bifidobacterium_pseudocatenulatum/Bifidobacterium_pseudocatenulatum_pangenome.tsv –o_matrix ./profiling_results/matrix.csv
> 
> STEP 1. Processing genes informations from pangenome file… Number of reference genomes: 18 Average number of gene-families per genome: 1761 Total number of pangenome gene-families 4550
> 
> STEP 2. Create coverage matrix Traceback (most recent call last): File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/bin/panphlan_profiling.py”, line 932, in main() File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/bin/panphlan_profiling.py”, line 864, in main dna_samples_covs = read_map_results(args.i_dna, args.verbose) File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/bin/panphlan_profiling.py”, line 299, in read_map_results dna_samples_covs[dna_sample_id] = read_gene_cov_file(os.path.join(i_dna, dna_covs_file)) File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/bin/panphlan_profiling.py”, line 285, in read_gene_cov_file for line in f: File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/lib/python3.7/bz2.py”, line 215, in readline return self._buffer.readline(size) File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/lib/python3.7/_compression.py”, line 68, in readinto data = self.read(len(byte_view)) File “/Users/wangzhenyu/opt/miniconda3/envs/panphlan/lib/python3.7/_compression.py”, line 103, in read data = self._decompressor.decompress(rawblock, size) OSError: Invalid data stream
> 
> Thanks for viewing! hope for your reply.

Hi! I'm having the same issue. How did you fix it? 
Best,

Pablo
