### ISSUE TITLE
panphlan_download_pangenome.py: number of retries

### ISSUE THREAD

**Issue by nick-youngblut** [SegataLab/panphlan#21]
`panphlan_download_pangenome.py` will sometimes fail due to download issues with dropbox. For example:

```
$ panphlan_download_pangenome.py -i Eubacterium_rectale
Downloading file of size: 0.24 MB
0.24 MB 100.64 %   9.33 MB/sec  0 min -0 sec
unable to download "https://www.dropbox.com/s/oz6uu7tjxuhfkei/Eubacterium_rectale.tar.bz2?dl=1"
```

The command was run successfully a couple of minutes later. It would be helpful to include parameters for number of retries and the time in between attempts.

**Comment by nick-youngblut** [comment]
It would also be nice if `panphlan_download_pangenome.py` automatically removed the `*.tar.bz2` file after uncompressing it

**Comment by nick-youngblut** [comment]
For anyone who wants a crude form of retrying:

```
#!/bin/bash
LOG=log.txt
for i in {1..5}; do
    panphlan_download_pangenome.py -i Eubacterium_rectale 2> $LOG 1>&2
    if grep -q "Pangenome not found." $LOG; then
	echo "Pangenome not found; retrying in 30 sec"
	sleep 30
    else
	echo "Pangenome found; finished"
	break
    fi
done
```

It's odd that `panphlan_download_pangenome.py` doesn't thrown an error if the pangenome isn't found. It exits with a status of 0, which is why I had to grep the log.

**Comment by leonarDubois** [comment]
Hello Nick, 

I just saw your issue, (and all the others you raised yesterday). Thanks a lot for the time you took to report all that and write all the suggestions. It will definitely be a great improvement. I'll gladly work on all of this between other projects. So, expect a PanPhlAn 3.1 in the beginning of 2021.

Best regards

**Comment by nick-youngblut** [comment]
Thanks for the update! I was trying to get it working, but without forking panphlan3 & re-writing some of the code, it likely won't work with our cluster setup (mainly due to https://github.com/SegataLab/panphlan/issues/22).

**Comment by leonarDubois** [comment]
Hi ! The version 3.1 is out and should fix the main issues you raised. (Thanks again for helping to PanPhlAn improvement).
The bioconda is updated, tmp location during mapping can be manually specified, pangenome download will retry several times in case of fail,  and profiling input can be a folder or a file containing the list of paths

Hope this will ease your analysis.

**Comment by nick-youngblut** [comment]
Awesome! I'll get the newest version a try ASAP

**Comment by nick-youngblut** [comment]
`--tmp` works for `panphlan_map.py`, but the user must create the directory beforehand; otherwise, the script throws an error. You might want to include `os.makedirs(args.tmp)` to prevent that issue. Does `panphlan_map.py` automatically delete the temp directory?

Thanks for adding `--tmp`!

**Comment by nick-youngblut** [comment]
Any possibility of supporting minimap2, given that it is substantially faster than bowtie2?

**Comment by leonarDubois** [comment]
Thanks, I'll push a tiny correction to create tmp if it doesn't exist. make sense.

On the short term, we don't really have plans to improve PanPhlAn by speeding it up. Mid-term goal is to extend the pangenome database. But I'll give a look at minimap2, thanks for the suggestion

**Comment by nick-youngblut** [comment]
Thanks for the info! Using an interval tree might speed up PanPhlAn more, at least for the processing of the BAM results. I've found minimap2 to work quite well with less issues that bowtie2
