### ISSUE TITLE
reference pangenome not available

### ISSUE THREAD

**Issue by xzl0034** [SegataLab/panphlan#30]
I am working with some human microbiome sample. And wish to use PanPhlan for the analysis of the strain (Collinsella_aerofaciens). But it is not available for downloading. 
What should I do?
Thanks!

**Comment by leonarDubois** [comment]
Hello, 

if the species pangenome is not available via `panphlan_download_pangenome.py ` it means that at the time we generate the database, only 1 genome was available. 

If you have at least 2 reference genomes available, you can construct your own custom pangenome for PanPhlAn using the [pangenome exporter](https://github.com/SegataLab/PanPhlAn_pangenome_exporter)

Best regards
Léonard

**Comment by xzl0034** [comment]
Thanks Léonard. I will build the pan genome with the pangenome exporter.
