### ISSUE TITLE
panphlan_map.py (ERR): bowtie2-align exited with value 134 'std::bad_alloc'

### ISSUE THREAD

**Issue by Gargari** [SegataLab/panphlan#32]
Hi, I would like to use panphlan but I cannot get over this error.

```
panphlan_map.py -p A.muciniphila_download/Akkermansia_muciniphila/Akkermansia_muciniphila_pangenome.tsv --indexes A.muciniphila_download/Akkermansia_muciniphila/Akkermansia_muciniphila -i fna/ZellerZ.fasta
 -o map_results/ZellerZ2.csv --fasta --verbose
```
 results:

 STEP 1. Checking software...
[I] Bowtie2 is installed
    version: 2.4.2, path: /root/miniconda3/envs/panphlan/bin/bowtie2
[I] Samtools version 1.11;  path: /root/miniconda3/envs/panphlan/bin/samtools

STEP 2.  Mapping the reads...
[I] input_path
[I] bowtie2 --very-sensitive --no-unal -x A.muciniphila_download/Akkermansia_muciniphila/Akkermansia_muciniphila -U - -p 5 -f
[I] Created temporary file /tmp/panphlan_ne_tedy1.sam
[W] Please wait. The computation may take several minutes...
[I] SAM records filtering: mismatches threshold is at -1, length threshold is at 70
**terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
(ERR): bowtie2-align exited with value 134**
[I] Rejected 0 reads over 662 total
Bowtie2 mapping and SAM filtering completed.
[I] Samtools version 1.11;  path: /root/miniconda3/envs/panphlan/bin/samtools
[I] samtools view -bS /tmp/panphlan_ne_tedy1.sam
[I] Temporary .bam file has been generated
[I] cmd (v1.11): samtools sort -m 4294967296 -o /tmp/panphlan_quksl8pj.bam
[I] .bam file /tmp/panphlan_quksl8pj.bam has been sorted
Samtools SAM->BAM translation (view+sort) completed.

STEP 3. Piling up...
[I] samtools index /tmp/panphlan_quksl8pj.bam
[I] BAM file /tmp/panphlan_quksl8pj.bam has been indexed
[I] samtools mpileup /tmp/panphlan_quksl8pj.bam > /tmp/panphlan_jps2h_ri.csv
[mpileup] 1 samples in 1 input files
Samtools piling up (view+mpileup) completed.

STEP 4. Exporting results...
Dictionary for {contig:{gene:(from,to)}} has been created.
[W] Please wait. The computation may take several minutes...
Gene abundances computing has just been completed.
[TERMINATING...] /root/miniconda3/envs/panphlan/bin/panphlan_map.py, 0.1 minutes.
 
 (I tried to use tar.gz input format: "fna/ZellerZ.tar.gz" too) 
 
 It looks like a memory problem... I have more than 100GB free space on my laptop and 32GB of RAM.

**Comment by leonarDubois** [comment]
Hello,

I would focus on the input provided. How big is it ? What does it contain ? 
Using one shotgun metagenomic sample (short reads) as input should be fine. Is it something else ?

**Comment by leonarDubois** [comment]
Well, if your question is to which subgroup of A. muciniphila your strain belong to, and if you're not especially interested in the gene content of it, then I advise you to use StrainPhlAn instead of PanPhlAn.

You'll find the StrainPhlAn software included in MetaPhlAn [here](https://github.com/biobakery/metaphlan). It will allow you to build a phylogenetic tree of all strains and reference genomes. You can then see in which branch your strain of interest fall in.
