### ISSUE TITLE
<mpileup> Set max per-file depth to 8000: What is it?

### ISSUE THREAD

**Issue by namdeka** [SegataLab/panphlan#33]
I was running the mapping step in the tutorial and this keeps happening: 

python panphlan/panphlan_map.py -i samples_fastq/CCMD34381688ST-21-0.fastq --indexes Eubacterium_rectale/Eubacterium_rectale -p Eubacterium_rectale/Eubacterium_rectale_pangenome.tsv -o map_results/CCMD34381688ST-21-0_erectale.tsv
[I] Bowtie2 is installed
    version: 2.2.6, path: /util/academic/bowtie/bowtie2-2.2.6/bowtie2
[I] Samtools version 1.3;  path: /util/common/bioinformatics/htslib/samtools/samtools
[I] bowtie2 --very-sensitive --no-unal -x Eubacterium_rectale/Eubacterium_rectale -U samples_fastq/CCMD34381688ST-21-0.fastq -p 12 --quiet
[I] Rejected 0 reads over 1984864 total
Bowtie2 mapping and SAM filtering completed.
[I] Samtools version 1.3;  path: /util/common/bioinformatics/htslib/samtools/samtools
[I] samtools view -bS /tmp/panphlan_l7rju74e.sam
[I] samtools index /tmp/panphlan_semabk0f.bam
[I] samtools mpileup /tmp/panphlan_semabk0f.bam > /tmp/panphlan_er9_jft8.csv
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000

**Comment by leonarDubois** [comment]
Hi!

Does this make the program stop ?
I'm use to run it with samtools 1.10. Might come from the different version. 

Leonard

**Comment by namdeka** [comment]
Yes, it was making the program stop. Using a higher version of samtools resolved the problem. Thank you. 

But I keep running out of time when running this. Does the run time depend on the file size?

**Comment by leonarDubois** [comment]
I guess yes, runtime might depends on the size of the input. But what you mention might be more a bowtie related issue I think
