### ISSUE TITLE
Duplicate sequence in Cardiobacterium hominis pangenome

### ISSUE THREAD

**Issue by andrewjmc** [SegataLab/panphlan#34]
Hello,

The cardiobacterium hominis pangenome has a duplicate sequence `GG694028.1` which leads to samtools errors in the PanPhlAn process:

```
[W::sam_hdr_create] Duplicated sequence "GG694025.1" in file "/var/tmp/pbs.4832157[3].pbs/panphlan_nznoc28r.sam"
[E::sam_hrecs_update_hashes] Duplicate entry "GG694050.1" in sam header
samtools view: failed to add PG line to the header
samtools sort: failed to read header from "-"
samtools index: "/var/tmp/pbs.4832157[3].pbs/panphlan_h0grwgda.bam" is in a format that cannot be usefully indexed
[E] Samtools index encountered some error.
```

I presume I can just remove the sequence and regenerate the bowtie indexes, but this could also be rectified in the version shared.

Best wishes,

Andrew

**Comment by leonarDubois** [comment]
Hi!

Yes, indeed, we should work on cleaning the database and re uploading it.
In the meantime, running  the latest version of the `panphlan_clean_pangenome.py ` script should fix the problem.

Leonard

**Comment by andrewjmc** [comment]
Thanks @leonarDubois !
