### ISSUE TITLE
Where to download pangenome file of a species?

### ISSUE THREAD

**Issue by lz870718** [SegataLab/panphlan#4]
Hi, thank you so much for developing this fantastic tool!
Just wondering where I can download pangenome file from CHocoPhlAn export?

**Comment by leonarDubois** [comment]
Hello,

you can easily retrieve the pangenome file (as well as the contig fasta file and the bowtie2 indexes) using the `panphlan_dowload_pangenome.py` file from PanPhlAn 3.0
i just pushed a "beta" 3.0 version available [here](https://github.com/SegataLab/panphlan/tree/3.0)
Let me know if you encounter troubles while using it.

**Comment by lz870718** [comment]
Hi, I would also like to include my own fasta file (strain) in the pangenome.  I ran the panphlan_new_genome_generation.py to achieve it. But the script always requires the original pangenome file that doesn't contain my strain (panphlan_[NCBI_TAX_ID]_pangenome.csv).
Is there a way to incorporate my own strain? Thank you!

**Comment by leonarDubois** [comment]
Hi, if you want to build a custom pangenome, you can do that using PanPhlAn 1.3 with the `panphlan_pangenome_generation.py` (without "new" in the name, this one is only generating the bowtie2 indexes)

This old script requires Usearch v7  (careful, a newer version is available but not supported by PanPhlAn). [Usearch download page](https://www.drive5.com/usearch/)

It will need you to provide either ffn and fna files, or gff and fna (or gff only in special cases, if gff includes sequences as well ). Basically you need to provide both sequences and annotations. 
The wiki page associated to this PanPhlAn 1.3 feature can be found [here](https://github.com/SegataLab/panphlan/wiki/Pangenome-generation-(old))

**Comment by lz870718** [comment]
Thank you. I have the fna file. But how can I generate the ffn/gff annotation with it? Any suggestion is appreciated!

**Comment by leonarDubois** [comment]
Prokka could be a nice tool for prokaryotic genome annotation 
[Prokka](https://github.com/tseemann/prokka)

**Comment by lz870718** [comment]
Thank you. I will try it out.
