### ISSUE TITLE
about the filename extension

### ISSUE THREAD

**Issue by dytk2134** [SegataLab/panphlan#6]
Hi all,
I am encountering the following error when running the panphlan_map.py script with a `.tar.bz2` file:
```
Error: reads file does not look like a FASTQ file
terminate called after throwing an instance of 'int'
Aborted (core dumped)
(ERR): bowtie2-align exited with value 134
```
This error may stem from this: 
https://github.com/SegataLab/panphlan/blob/3.0/panphlan_map.py#L103

```
>>> os.path.splitext("Sample.tar.bz2")
('Sample.tar', '.bz2')
```
The extension of `Sample.tar.bz2` is `.bz2` not `tar.bz2`

**Comment by dytk2134** [comment]
https://github.com/SegataLab/panphlan/blob/3.0/panphlan_map.py#L104-L107
```
    if extension in decompress_cmd.keys():
        to_do = decompress_cmd[extension]
        to_do.append(input)
        print('[I] ' + ' '.join(to_do))
```

https://github.com/SegataLab/panphlan/blob/3.0/panphlan_map.py#L196
```
        if preprocess_needed:
            p0 = subprocess.Popen(preprocess_needed, stdout=subprocess.PIPE)
```

**Comment by leonarDubois** [comment]
Hello, 
thanks a lot for highlighting this issue. I pushed a small correction. Let me know if there is still something wrong.

**Comment by dytk2134** [comment]
Hi there,
I got SyntaxError...
```
  File "/home/dytk2134/project/shotgun_sequencing/tools/panphlan/panphlan_map.py", line 107
    print('[I] ' + ' '.join(input_path))
        ^
SyntaxError: invalid syntax
```
Here has an open parenthesis
https://github.com/SegataLab/panphlan/blob/3.0/panphlan_map.py#L106

After fixing this error will get this error message
```
[I] Bowtie2 is installed
    version: 2.3.5.1, path: /home/dytk2134/miniconda3/envs/arg_env/bin/bowtie2
[I] Samtools version 1.9;  path: /home/dytk2134/miniconda3/envs/arg_env/bin/samtools
[I] . . / k p _ p a n p h l a n / p a n p h l a n / S A M 0 2 . t a r . b z 2
Traceback (most recent call last):
  File "/home/dytk2134/project/shotgun_sequencing/tools/panphlan/panphlan_map.py", line 395, in <module>
    main()
  File "/home/dytk2134/project/shotgun_sequencing/tools/panphlan/panphlan_map.py", line 380, in main
    tmp_sam =  mapping(args)
  File "/home/dytk2134/project/shotgun_sequencing/tools/panphlan/panphlan_map.py", line 195, in mapping
    p0 = subprocess.Popen(cmd1, stdout=subprocess.PIPE)
NameError: name 'cmd1' is not defined
```
This error may stem from this:
https://github.com/SegataLab/panphlan/blob/3.0/panphlan_map.py#L195

**Comment by leonarDubois** [comment]
Ok, sorry, I tried to correct it a bit too quickly.
I pushed a new correction that should work better. Can you try again, please ?

**Comment by dytk2134** [comment]
Thanks, it works!
