### ISSUE TITLE
 HUMAnN2_CHOCOPhlAn_201901_functional_annotation_mapping.tsv

### ISSUE THREAD

**Issue by fconstancias** [SegataLab/panphlan#7]
Dear panphlan developers,

Is there an easy way to get the HUMAnN2_CHOCOPhlAn_201901_functional_annotation_mapping.tsv in order to add it as --funct_annot during the panphlan_profiling.py step, 
as shown in the tutorial <https://github.com/SegataLab/panphlan/wiki/PanPhlAn-profiling-3_0> ?

Thanks.

**Comment by leonarDubois** [comment]
Hi, it is planned and should be added soon ;)

**Comment by leonarDubois** [comment]
Hello,

we updated the pangenome database. A few species were discarded, some include now more reference genomes and a mapping file is available in the pangeome folder. It's a tsv mapping UniRef90 to KEGG, GO, Pfam, eggNOG... only for the UniRef90 found in the given species pangenome.

**Comment by fconstancias** [comment]
Hi @leonarDubois, could you indicate the link of the tsv mapping file please?

**Comment by leonarDubois** [comment]
Hi,

the tsv file is now included in the pangenome folder. You can get it for one species by downloading it using `panphlan_download_pangenome.py`
